name: Build CI
on:
  pull_request:
  push:
    branches:
      - 'master'
env:
  FLOPPA_MONGO_CONNECTION_STRING: 'mongodb+srv://aemond:LQFBM2LFCS8fgTUa@local-antoine.eivt9.mongodb.net/Floppa?retryWrites=true&w=majority'
  FLOPPA_MONGO_DATABASE: Floppa

jobs:
  checkstyle-and-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven

      - name: Step 1 Checkstyle
        run: mvn checkstyle:check

      - name: Step 2 Compile
        run: mvn compile

      - name: Step 3 Tests
        run: mvn verify