name: Deploy Production (Manual)
on:
  workflow_dispatch:
    inputs:
      target:
        description: 'Target (Commit, Branch, Tag)'
        required: true
env:
  PORT: 8080

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{github.event.inputs.target}}
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven

      - name: MongoDB in GitHub Actions
        uses: supercharge/mongodb-github-action@1.7.0

      - name: Step 1 Checkstyle
        run: mvn checkstyle:check

      - name: Step 2 Compile
        run: mvn compile

      - name: Step 3 Tests
        run: mvn verify

  deploy-production:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target (Manual)
        uses: actions/checkout@v2
        with:
          ref: ${{github.event.inputs.target}}

      - name: Deploy to Heroku (Prod)
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: production-team20floppa
          heroku_email: maxime.imbeau@hotmail.com
          healthcheck: "https://production-team20floppa.herokuapp.com/health"
          rollbackonhealthcheckfailed: true
          delay: 5

