name: Java CI
on:
  pull_request:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      
      - name: Step 1 Checkstyle
      - run: mvn checkstyle:check
      
      - name: Step 2 Compile
      - run: mvn compile -Dcheckstyle.skip
